spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop\
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://cicd-test-db.claqrfmnuels.ap-northeast-2.rds.amazonaws.com:3306/jpashop
    username: admin
    password: jykim0506
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
